[package]
name = "learning_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reduce = "0.1.4"
itertools = "0.7.4"
num-bigint = "0.4.0"
num = "0.4.0"
permutator = "0.4.0"